db:  
  image: postgres
  environment:
    - POSTGRES_USER=temp 
    - POSTGRES_PASSWORD=temp
dev2:  
  build: .
  ports:
    - '8080:8080'
  links:
    - db
  environment:
    - PGHOST=db
    - DATABASE_URL=postgres://temp:temp@db:5432/temp